name: psf_3
channels:
- http://ssb.stsci.edu/astroconda
- defaults
dependencies:
- matplotlib
- numpy
- pip
- python
- pyyaml
- scipy
- sqlalchemy
- pip:
  - astropy
  - bokeh
  - montage-wrapper
  - pymysql
