python make_ir_psf_table.py -filter F105W
python make_ir_psf_table.py -filter F110W
python make_ir_psf_table.py -filter F125W
python make_ir_psf_table.py -filter F140W
python make_ir_psf_table.py -filter F160W
python make_ir_psf_table.py -filter F098M
python make_ir_psf_table.py -filter F127M
python make_ir_psf_table.py -filter F139M
python make_ir_psf_table.py -filter F153M
python make_ir_psf_table.py -filter F126N
python make_ir_psf_table.py -filter F128N
python make_ir_psf_table.py -filter F130N
python make_ir_psf_table.py -filter F132N
python make_ir_psf_table.py -filter F164N
python make_ir_psf_table.py -filter F167N
